// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw_Ln01ecNfwvSW2LbE910dd9sgQc1lCU',
    appId: '1:668782306511:web:af3d8295cfae4c1ae643ba',
    messagingSenderId: '668782306511',
    projectId: 'medical-internship-boumerdes',
    authDomain: 'medical-internship-boumerdes.firebaseapp.com',
    storageBucket: 'medical-internship-boumerdes.firebasestorage.app',
    measurementId: 'G-8GFY2MLPNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7Le7EDZfWDWlTiYRVR0O2WONTxRg0GzY',
    appId: '1:668782306511:android:c386494936f622f1e643ba',
    messagingSenderId: '668782306511',
    projectId: 'medical-internship-boumerdes',
    storageBucket: 'medical-internship-boumerdes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBbUjX0W-zxqZqTcBqiXWYKKmDbpYDrlo',
    appId: '1:668782306511:ios:8db771bda99f233ae643ba',
    messagingSenderId: '668782306511',
    projectId: 'medical-internship-boumerdes',
    storageBucket: 'medical-internship-boumerdes.firebasestorage.app',
    iosBundleId: 'com.example.med',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBbUjX0W-zxqZqTcBqiXWYKKmDbpYDrlo',
    appId: '1:668782306511:ios:8db771bda99f233ae643ba',
    messagingSenderId: '668782306511',
    projectId: 'medical-internship-boumerdes',
    storageBucket: 'medical-internship-boumerdes.firebasestorage.app',
    iosBundleId: 'com.example.med',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw_Ln01ecNfwvSW2LbE910dd9sgQc1lCU',
    appId: '1:668782306511:web:de6dd7b08e9b1d7ae643ba',
    messagingSenderId: '668782306511',
    projectId: 'medical-internship-boumerdes',
    authDomain: 'medical-internship-boumerdes.firebaseapp.com',
    storageBucket: 'medical-internship-boumerdes.firebasestorage.app',
    measurementId: 'G-J8N6BNEQ6Q',
  );
}
